name: Deploy Nightly
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  nightly:
    name: Re-build nightly
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - uses: actions/checkout@master
      - name: Docker Build & Push
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: troyfontaine/php72-laravel
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
