name: Deploy Nightly
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  nightly:
    name: Re-build nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Registry
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN

      - name: Generate Git Hash Variable
        run: echo ::set-env name=GIT_HASH::$(git rev-parse --short HEAD)

      - name: Generate Date-Time Variable
        run: echo ::set-env name=DATE_TAG::$(date +"%m-%d-%y")-$GIT_HASH

      - name: Building Docker Image
        run:
          docker build --no-cache --compress -t "$CONTAINER_IMAGE_NAME:$DATE_TAG" -t "$CONTAINER_IMAGE_NAME:latest" .

      - name: Push Docker Image
        run: docker push "$CONTAINER_IMAGE_NAME:latest"
