---
name: Open Pull Request

on: [pull_request]

jobs:
  run_checks:
    name: Run Linter
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.1
          TARGET: Dockerfile

        
  build_amd64:
    name: Build code on AMD64 Architecture
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: docker build testimage:latest .
