---
name: Open Pull Request

on: [pull_request]

env:
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  run_checks:
    name: Run Linter
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

  build_amd64:
    name: Build code on AMD64 Architecture
    runs-on: ubuntu-latest
    needs: [run_checks]
    steps:
      - uses: actions/checkout@v2
      - name: Generate Git Hash Variable
        run: echo ::set-env name=GIT_HASH::$(git rev-parse --short HEAD)
      - name: Generate Date-Time Variable
        run: echo ::set-env name=DATE_TAG::$(date +"%m-%d-%y")-$GIT_HASH
      - name: Build image
        run: docker build --compress --no-cache -t "$DOCKER_IMAGE_NAME:$GIT_HASH" -t "$DOCKER_IMAGE_NAME:$DATE_TAG" .
